### ISSUE TITLE
Error AUDIO_OUTPUT_FLAG_FAST denied by server

### ISSUE THREAD

**Issue by GaelleJoubert** [eopeter/flutter_dtmf#15]
Since the last commit I have a new error, both on my Pixel 6A and a Sony Xperia.

The error is the following :
```
AUDIO_OUTPUT_FLAG_FAST denied by server;
E/AudioTrack(21895): AudioFlinger could not create track, status: -12
E/ToneGenerator(21895): AudioTrack(0x7e49992400) set failed with error -12
```
The weird thing is that the plugging do work without error on my Samsunf A52.

I digged the code a little bit and found a fix that seems to fix my error on both phone. I'll submit a pull request.

**Comment by eopeter** [comment]
So the PR did not fix this issue?

**Comment by GaelleJoubert** [comment]
Not really. I was a bit fast.
It did fix the issue on the Xperia, but then I realised, after a while and at high frequency this issue appeared even on my other phones.
So I need to dig a little bit more. Because I do not have this issue with version 3.0.1. 
So I am working on it to see what exactly cause It.
I'll do another PR when I find it.

**Comment by GaelleJoubert** [comment]
fixed in my last PR !
