### ISSUE TITLE
No working on a Android Tablet

### ISSUE THREAD

**Issue by GaelleJoubert** [eopeter/flutter_dtmf#17]
I ran my app on the following Android tablet :  RugGEAR RG910, Android 8.0.0.
The code I used is  the same I use and tested on several phones : Samsung A52, Pixel 6a, Pixel 4a, and a Xperia. 
It works on all the phones.

On the tablet, I know the function is called, but no sound is played.
No error is displayed.
Of course I checked that the sound is on.

I also tried to run the exemple code, and it run with the exact same behaviour : no sound but no error on the tablet.
(I also run the exemple on my ohines for comparisons and it works)

I have no idea if the isuue is fom the tablet itself or its Android version. 
Could anyone try to Run the exemple in another Android tablet and tell me if they have the same issue ?

**Comment by GaelleJoubert** [comment]
Additional information, I have another app on this tablet, coded not in flutter, but in Java, it also uses Tone Generator, and it does work well ...

**Comment by GaelleJoubert** [comment]
Ok; I have found and fix the issue : 
The issue was coming from this line : 

```
isDtmfToneDisabled = Settings.System.getInt(
                        applicationContext.contentResolver,
                        Settings.System.DTMF_TONE_WHEN_DIALING, 1
                ) == 0;
```
On the tablet DTMF Tone was indeed disable, but I still want to play the sound. 
So I have added an option to "force play" the sound.

**Comment by eopeter** [comment]
I do see some weird behavior on Android and I think more research is needed to fully resolve but it is always the right thing to respect the system settings or atleast make that the default and have an option to not use it.

**Comment by GaelleJoubert** [comment]
> I do see some weird behavior on Android and I think more research is needed to fully resolve but it is always the right thing to respect the system settings or atleast make that the default and have an option to not use it.

Yes, that was my idea, I'll add an option to "force play" the sound, but it will not be activated by default. 
I am working on the other issue now, but my PR will include that.

**Comment by GaelleJoubert** [comment]
fixed in my last PR !
