### ISSUE TITLE
Can we set the Volume of the dtmf?

### ISSUE THREAD

**Issue by marcodecarolisidt** [eopeter/flutter_dtmf#8]
It would be great if it follows the platform settings

**Comment by aytunch** [comment]
I need the same functionality. Is this package being maintained @eopeter ?

**Comment by eopeter** [comment]
Yes

**Comment by aytunch** [comment]
Hi @eopeter thanks for the reply.
Do you have any plans to add volume functionality?
Or can you point us to the right direction?
Do the underlying native libraries support setting volume?

**Comment by eopeter** [comment]
Volume control added in plugin v3.0.0

**Comment by aytunch** [comment]
Thank you :)
